# Generated by Django 3.0.6 on 2020-05-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slut',
            new_name='slug',
        ),
    ]
